# Generated by Django 6.0.6 on 2026-07-09 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixelGridConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_width', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('grid_height', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('pixel_price_usd', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('pixel_price_clp', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Grilla',
                'verbose_name_plural': 'Configuraciones de Grilla',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('access_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('search_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('display_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('main_image', models.ImageField(max_length=500, upload_to='pixels/%Y/%m/%d/')),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_message', models.TextField(blank=True, max_length=500)),
                ('purchase_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_clp', models.IntegerField(blank=True, null=True)),
                ('payment_currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('CLP', 'CLP')], max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('stripe_payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('pending_payment', 'Pago Pendiente')], default='pending_payment', max_length=20)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('moderation_reason', models.TextField(blank=True)),
                ('moderation_flagged_categories', models.JSONField(blank=True, default=list)),
                ('views_count', models.IntegerField(default=0)),
                ('shares_count', models.JSONField(blank=True, default=dict)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['x', 'y'], name='pixels_pixe_x_1453f3_idx'), models.Index(fields=['access_code'], name='pixels_pixe_access__383260_idx'), models.Index(fields=['search_code'], name='pixels_pixe_search__3dec4c_idx'), models.Index(fields=['display_code'], name='pixels_pixe_display_e1f4ce_idx'), models.Index(fields=['owner_email'], name='pixels_pixe_owner_e_b9172c_idx'), models.Index(fields=['status', 'moderation_status'], name='pixels_pixe_status_d9e96d_idx'), models.Index(fields=['-purchased_at'], name='pixels_pixe_purchas_1eb804_idx')],
                'unique_together': {('x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='PixelPurchaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('pixel_x', models.IntegerField()),
                ('pixel_y', models.IntegerField()),
                ('images_data', models.JSONField(default=list)),
                ('image_filenames', models.JSONField(default=list)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_message', models.TextField(blank=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='pixels_pixe_session_1f357e_idx'), models.Index(fields=['expires_at'], name='pixels_pixe_expires_8d3da3_idx'), models.Index(fields=['payment_intent_id'], name='pixels_pixe_payment_771057_idx')],
            },
        ),
        migrations.CreateModel(
            name='PixelViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.GenericIPAddressField()),
                ('viewer_user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='pixels.pixel')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['pixel', 'viewed_at'], name='pixels_pixe_pixel_i_db44c5_idx'), models.Index(fields=['viewed_at'], name='pixels_pixe_viewed__64a02b_idx')],
            },
        ),
    ]
