# Generated by Django 5.1 on 2026-07-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pixels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pixelpurchasesession',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pixel',
            index=models.Index(fields=['owner'], name='pixels_pixe_owner_i_ee5884_idx'),
        ),
        migrations.AddIndex(
            model_name='pixelpurchasesession',
            index=models.Index(fields=['owner'], name='pixels_pixe_owner_i_4865d7_idx'),
        ),
    ]
